# Generated by Django 4.2.17 on 2026-05-22 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0013_character_is_narrator_character_reference_audio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='引擎名称')),
                ('engine_type', models.CharField(choices=[('gpt_sovits', 'GPT-SoVITS'), ('cosyvoice', 'CosyVoice'), ('xtts', 'XTTS'), ('indextts', 'IndexTTS'), ('fish_speech', 'Fish Speech'), ('edge_tts', 'Edge TTS')], max_length=20, verbose_name='引擎类型')),
                ('description', models.TextField(blank=True, verbose_name='引擎描述')),
                ('api_url', models.URLField(blank=True, verbose_name='API 地址')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('is_local', models.BooleanField(default=True, verbose_name='是否本地部署')),
                ('default_params', models.JSONField(default=dict, help_text='如 {"speed": 1.0, "temperature": 0.7}', verbose_name='默认参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认引擎')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='优先级')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'TTS 引擎',
                'verbose_name_plural': 'TTS 引擎',
                'ordering': ['-is_default', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TTSGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('preparing', '准备中'), ('generating', '生成中'), ('merging', '合并中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度百分比')),
                ('script_data', models.JSONField(default=list, help_text='[{speaker, text, emotion, voice_asset_id}, ...]', verbose_name='剧本数据')),
                ('speaker_voice_map', models.JSONField(default=dict, help_text='{speaker_name: voice_asset_id}', verbose_name='角色语音映射')),
                ('generation_params', models.JSONField(default=dict, verbose_name='生成参数')),
                ('output_dir', models.CharField(blank=True, max_length=500, verbose_name='输出目录')),
                ('merged_audio_path', models.CharField(blank=True, max_length=500, verbose_name='合并音频路径')),
                ('total_segments', models.PositiveIntegerField(default=0, verbose_name='总片段数')),
                ('completed_segments', models.PositiveIntegerField(default=0, verbose_name='已完成片段数')),
                ('failed_segments', models.PositiveIntegerField(default=0, verbose_name='失败片段数')),
                ('total_duration', models.FloatField(blank=True, null=True, verbose_name='总时长(秒)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('processing_log', models.TextField(blank=True, verbose_name='处理日志')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tts_tasks', to='novels.chapter', verbose_name='关联章节')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_tasks', to='tts.ttsengine', verbose_name='使用引擎')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tts_tasks', to='novels.novel', verbose_name='所属小说')),
            ],
            options={
                'verbose_name': 'TTS 生成任务',
                'verbose_name_plural': 'TTS 生成任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='声音名称')),
                ('description', models.TextField(blank=True, verbose_name='声音描述')),
                ('voice_type', models.CharField(choices=[('narrator', '旁白'), ('male', '男声'), ('female', '女声'), ('child', '童声'), ('elderly', '老者'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='声音类型')),
                ('audio_file', models.FileField(upload_to='voices/', verbose_name='参考音频文件')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('sample_rate', models.IntegerField(blank=True, null=True, verbose_name='采样率')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('compatible_engines', models.JSONField(default=list, help_text='如 ["gpt_sovits", "cosyvoice"]', verbose_name='兼容引擎')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('tags', models.CharField(blank=True, help_text='逗号分隔的标签，如 温柔,沉稳,普通话', max_length=200, verbose_name='标签')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_assets', to='novels.character', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '语音资源',
                'verbose_name_plural': '语音资源',
                'ordering': ['-is_active', 'voice_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TTSSegmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='序列号')),
                ('speaker', models.CharField(max_length=100, verbose_name='说话人')),
                ('text', models.TextField(verbose_name='文本内容')),
                ('emotion', models.CharField(blank=True, max_length=50, verbose_name='情绪')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='generated_tts/', verbose_name='生成的音频文件')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_results', to='tts.ttsgenerationtask', verbose_name='所属任务')),
                ('voice_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tts.voiceasset', verbose_name='使用的语音')),
            ],
            options={
                'verbose_name': 'TTS 片段结果',
                'verbose_name_plural': 'TTS 片段结果',
                'ordering': ['task', 'sequence_number'],
                'unique_together': {('task', 'sequence_number')},
            },
        ),
    ]
