# Generated by Django 5.2.5 on 2026-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiceasset",
            name="audio_file",
            field=models.FileField(
                blank=True, null=True, upload_to="voices/", verbose_name="参考音频文件"
            ),
        ),
    ]
