# Generated by Django 5.2.5 on 2025-08-22 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='小说标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='novels/covers/', verbose_name='封面')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('voice_style', models.CharField(blank=True, max_length=50, verbose_name='语音风格')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='characters/avatars/', verbose_name='头像')),
                ('is_main_character', models.BooleanField(default=False, verbose_name='是否主角')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.novel', verbose_name='所属小说')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['-is_main_character', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('chapter_number', models.PositiveIntegerField(verbose_name='章节序号')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel', verbose_name='所属小说')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['novel', 'chapter_number'],
                'unique_together': {('novel', 'chapter_number')},
            },
        ),
        migrations.CreateModel(
            name='NovelTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='novels.novel')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_relations', to='novels.noveltag')),
            ],
            options={
                'verbose_name': '小说标签关联',
                'verbose_name_plural': '小说标签关联',
                'unique_together': {('novel', 'tag')},
            },
        ),
    ]
