# Generated by Django 4.2.7 on 2025-08-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_sort_number',
            field=models.PositiveIntegerField(default=0, verbose_name='章节排序数字'),
        ),
    ]
