# Generated by Django 4.2.7 on 2025-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_add_chapter_sort_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['novel', 'chapter_sort_number'], 'verbose_name': '章节', 'verbose_name_plural': '章节'},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('novel', 'chapter_sort_number')},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.CharField(help_text='支持中文数字，如"一千一百八十八"', max_length=50, verbose_name='章节序号'),
        ),
    ]
