# Generated by Django 5.2.5 on 2025-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_chapter_options_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.CharField(blank=True, help_text='章节所属卷的信息，如"第十一卷真仙降世"', max_length=200, null=True, verbose_name='卷信息'),
        ),
    ]
