# Generated by Django 4.2.7 on 2025-08-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_chapter_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='source_url',
            field=models.URLField(blank=True, help_text='第一章或目录页面的URL', null=True, verbose_name='来源链接'),
        ),
    ]
