# Generated by Django 4.2.7 on 2025-08-24 02:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_novel_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='来源名称')),
                ('source_type', models.CharField(choices=[('example_site', '示例站点'), ('custom', '自定义')], default='example_site', max_length=20, verbose_name='来源类型')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('chapter_url_pattern', models.CharField(blank=True, max_length=200, verbose_name='章节URL模式')),
                ('encoding', models.CharField(default='utf-8', max_length=20, verbose_name='页面编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.PositiveIntegerField(default=1, help_text='数字越大优先级越高', verbose_name='优先级')),
                ('last_crawl_at', models.DateTimeField(blank=True, null=True, verbose_name='最后爬取时间')),
                ('crawl_count', models.PositiveIntegerField(default=0, verbose_name='爬取次数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小说来源',
                'verbose_name_plural': '小说来源',
                'ordering': ['-priority', 'source_type'],
            },
        ),
        migrations.RemoveField(
            model_name='novel',
            name='source_url',
        ),
        migrations.CreateModel(
            name='NovelSourceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='具体的小说页面URL', verbose_name='来源URL')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主来源')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('sync_count', models.PositiveIntegerField(default=0, verbose_name='同步次数')),
                ('chapter_count', models.PositiveIntegerField(default=0, verbose_name='来源章节数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='小说')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novelsource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '小说来源关联',
                'verbose_name_plural': '小说来源关联',
                'ordering': ['-is_primary', '-last_sync_at'],
                'unique_together': {('novel', 'source')},
            },
        ),
    ]
