# Generated by Django 5.2.5 on 2025-08-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_novelsource_remove_novel_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='source_url',
            field=models.URLField(blank=True, help_text='该章节的原始URL链接', null=True, verbose_name='来源链接'),
        ),
        migrations.AlterField(
            model_name='novelsource',
            name='source_type',
            field=models.CharField(help_text='网站类型或分类', max_length=50, verbose_name='来源类型'),
        ),
    ]
