# Generated by Django 4.2.7 on 2025-08-30 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0008_chapter_source_url_alter_novelsource_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(verbose_name='目录源URL')),
                ('title', models.CharField(max_length=200, verbose_name='小说标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('total_chapters', models.IntegerField(default=0, verbose_name='总章节数')),
                ('chapters_data', models.JSONField(default=list, verbose_name='章节数据')),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name='提取时间')),
                ('extractor_version', models.CharField(blank=True, max_length=50, verbose_name='提取器版本')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('novel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='novels.novel', verbose_name='关联小说')),
            ],
            options={
                'verbose_name': '小说目录',
                'verbose_name_plural': '小说目录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('task_type', models.CharField(choices=[('catalog_extract', '目录提取'), ('chapter_download', '章节下载'), ('batch_import', '批量导入')], max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('source_url', models.URLField(verbose_name='源URL')),
                ('parameters', models.JSONField(default=dict, verbose_name='任务参数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('result_data', models.JSONField(default=dict, verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('total_items', models.IntegerField(default=0, verbose_name='总项目数')),
                ('processed_items', models.IntegerField(default=0, verbose_name='已处理项目数')),
                ('success_items', models.IntegerField(default=0, verbose_name='成功项目数')),
                ('failed_items', models.IntegerField(default=0, verbose_name='失败项目数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='关联小说')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '爬虫任务',
                'verbose_name_plural': '爬虫任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'DEBUG'), ('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR'), ('critical', 'CRITICAL')], max_length=20, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='novels.crawlertask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '爬虫日志',
                'verbose_name_plural': '爬虫日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('config_type', models.CharField(choices=[('site_config', '站点配置'), ('selector_config', '选择器配置'), ('request_config', '请求配置')], max_length=50, verbose_name='配置类型')),
                ('site_domain', models.CharField(max_length=200, verbose_name='站点域名')),
                ('config_data', models.JSONField(default=dict, verbose_name='配置数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '爬虫配置',
                'verbose_name_plural': '爬虫配置',
                'ordering': ['-priority', 'site_domain'],
                'unique_together': {('name', 'site_domain')},
            },
        ),
        migrations.CreateModel(
            name='ChapterDownloadRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('chapter_number', models.IntegerField(verbose_name='章节号')),
                ('source_url', models.URLField(verbose_name='章节源URL')),
                ('status', models.CharField(choices=[('pending', '等待下载'), ('downloading', '下载中'), ('completed', '下载完成'), ('failed', '下载失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='下载状态')),
                ('content_length', models.IntegerField(default=0, verbose_name='内容长度')),
                ('watermark_removed', models.BooleanField(default=False, verbose_name='是否去除水印')),
                ('download_started_at', models.DateTimeField(blank=True, null=True, verbose_name='下载开始时间')),
                ('download_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='下载完成时间')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.chapter', verbose_name='关联章节')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_records', to='novels.crawlertask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '章节下载记录',
                'verbose_name_plural': '章节下载记录',
                'ordering': ['task', 'chapter_number'],
                'unique_together': {('task', 'chapter_number')},
            },
        ),
    ]
