# Generated by Django 4.2.7 on 2025-08-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_novelcatalog_crawlertask_crawlerlog_crawlerconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='source_url',
            field=models.URLField(blank=True, help_text='小说的原始网址，用于自动爬取', null=True, verbose_name='源URL'),
        ),
    ]
