# Generated by Django 4.2.7 on 2025-08-30 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_novel_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDownloadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('source_url', models.URLField(verbose_name='小说源链接')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '下载中'), ('paused', '已暂停'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.FloatField(default=0.0, help_text='0-100的百分比', verbose_name='下载进度')),
                ('total_chapters', models.PositiveIntegerField(default=0, verbose_name='总章节数')),
                ('downloaded_chapters', models.PositiveIntegerField(default=0, verbose_name='已下载章节数')),
                ('failed_chapters', models.PositiveIntegerField(default=0, verbose_name='失败章节数')),
                ('auto_retry', models.BooleanField(default=True, verbose_name='自动重试')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='最大重试次数')),
                ('download_delay', models.FloatField(default=1.0, verbose_name='下载间隔(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('task_id', models.CharField(blank=True, max_length=100, verbose_name='后台任务ID')),
                ('novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.novel', verbose_name='关联小说')),
            ],
            options={
                'verbose_name': '批量下载任务',
                'verbose_name_plural': '批量下载任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('success', '成功')], default='info', max_length=20, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='章节号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='novels.batchdownloadtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '下载任务日志',
                'verbose_name_plural': '下载任务日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
