# Generated by Django 4.2.7 on 2025-08-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0011_batchdownloadtask_downloadtasklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReadingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_crawl_enabled', models.BooleanField(default=True, verbose_name='启用自动爬取')),
                ('crawl_ahead_chapters', models.PositiveIntegerField(default=3, verbose_name='提前爬取章节数')),
                ('font_size', models.PositiveIntegerField(default=16, verbose_name='字体大小')),
                ('line_height', models.FloatField(default=1.6, verbose_name='行高')),
                ('background_color', models.CharField(default='white', max_length=20, verbose_name='背景颜色')),
                ('reading_mode', models.CharField(choices=[('page', '翻页模式'), ('scroll', '连续模式')], default='page', max_length=20, verbose_name='阅读模式')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户阅读设置',
                'verbose_name_plural': '用户阅读设置',
            },
        ),
    ]
