# Generated by Django 4.2.17 on 2026-05-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_userreadingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_narrator',
            field=models.BooleanField(default=False, verbose_name='是否旁白'),
        ),
        migrations.AddField(
            model_name='character',
            name='reference_audio',
            field=models.FileField(blank=True, null=True, upload_to='characters/voices/', verbose_name='参考音频'),
        ),
        migrations.AddField(
            model_name='character',
            name='speaker_tag',
            field=models.CharField(blank=True, help_text='剧本中使用的说话人标识，如 韩立、旁白', max_length=50, verbose_name='说话人标签'),
        ),
        migrations.AddField(
            model_name='character',
            name='tts_voice_id',
            field=models.CharField(blank=True, help_text='Edge TTS 等引擎的音色标识', max_length=200, verbose_name='TTS 音色ID'),
        ),
    ]
