# Generated by Django 4.2.7 on 2025-08-30 14:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'system_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门编码')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='层级')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'system_department',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='字典类型')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'db_table': 'system_dict',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户账号')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='登录IP地址')),
                ('login_location', models.CharField(blank=True, max_length=255, verbose_name='登录地点')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='浏览器类型')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('status', models.CharField(max_length=1, verbose_name='登录状态')),
                ('msg', models.CharField(blank=True, max_length=255, verbose_name='提示消息')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'system_login_log',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('menu_type', models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('F', '按钮')], max_length=1, verbose_name='菜单类型')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=200, verbose_name='组件路径')),
                ('perms', models.CharField(blank=True, max_length=100, verbose_name='权限标识')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='菜单图标')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='显示排序')),
                ('visible', models.BooleanField(default=True, verbose_name='显示状态')),
                ('is_frame', models.BooleanField(default=False, verbose_name='是否外链')),
                ('is_cache', models.BooleanField(default=False, verbose_name='是否缓存')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'system_menu',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='模块标题')),
                ('business_type', models.IntegerField(choices=[(0, '其它'), (1, '新增'), (2, '修改'), (3, '删除'), (4, '授权'), (5, '导出'), (6, '导入'), (7, '强退'), (8, '生成代码'), (9, '清空数据')], default=0, verbose_name='业务类型')),
                ('method', models.CharField(max_length=100, verbose_name='方法名称')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方式')),
                ('operator_type', models.IntegerField(choices=[(1, '后台用户'), (2, '手机端用户')], default=1, verbose_name='操作类别')),
                ('oper_name', models.CharField(max_length=50, verbose_name='操作人员')),
                ('dept_name', models.CharField(blank=True, max_length=50, verbose_name='部门名称')),
                ('oper_url', models.CharField(max_length=255, verbose_name='请求URL')),
                ('oper_ip', models.GenericIPAddressField(verbose_name='主机地址')),
                ('oper_location', models.CharField(blank=True, max_length=255, verbose_name='操作地点')),
                ('oper_param', models.TextField(blank=True, verbose_name='请求参数')),
                ('json_result', models.TextField(blank=True, verbose_name='返回参数')),
                ('status', models.IntegerField(default=0, verbose_name='操作状态')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误消息')),
                ('oper_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('cost_time', models.BigIntegerField(default=0, verbose_name='消耗时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'system_operation_log',
                'ordering': ['-oper_time'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色编码')),
                ('description', models.TextField(blank=True, verbose_name='角色描述')),
                ('data_scope', models.IntegerField(choices=[(1, '全部数据权限'), (2, '自定义数据权限'), (3, '本部门数据权限'), (4, '本部门及以下数据权限'), (5, '仅本人数据权限')], default=1, verbose_name='数据范围')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('departments', models.ManyToManyField(blank=True, to='system.department', verbose_name='数据权限部门')),
                ('menus', models.ManyToManyField(blank=True, to='system.menu', verbose_name='菜单权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'system_role',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='system.role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='字典标签')),
                ('value', models.CharField(max_length=100, verbose_name='字典键值')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('css_class', models.CharField(blank=True, max_length=100, verbose_name='样式属性')),
                ('list_class', models.CharField(blank=True, max_length=100, verbose_name='表格回显样式')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('is_active', models.BooleanField(default=True, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dict_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='system.dict', verbose_name='字典类型')),
            ],
            options={
                'verbose_name': '字典数据',
                'verbose_name_plural': '字典数据',
                'db_table': 'system_dict_data',
                'ordering': ['sort', 'id'],
                'unique_together': {('dict_type', 'value')},
            },
        ),
    ]
