# Generated by Django 5.2.5 on 2025-08-22 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audios', '0001_initial'),
        ('llms', '0001_initial'),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('voice_settings', models.JSONField(default=dict, verbose_name='语音设置')),
                ('quality_level', models.CharField(choices=[('draft', '草稿质量'), ('standard', '标准质量'), ('high', '高质量'), ('premium', '顶级质量')], default='standard', max_length=20, verbose_name='质量等级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('preparing', '准备中'), ('generating', '生成中'), ('post_processing', '后处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_segments', models.PositiveIntegerField(default=0, verbose_name='总片段数')),
                ('completed_segments', models.PositiveIntegerField(default=0, verbose_name='已完成片段数')),
                ('failed_segments', models.PositiveIntegerField(default=0, verbose_name='失败片段数')),
                ('output_file_path', models.CharField(blank=True, max_length=500, verbose_name='输出文件路径')),
                ('total_duration', models.FloatField(blank=True, null=True, verbose_name='总时长(秒)')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('processing_log', models.TextField(blank=True, verbose_name='处理日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('audio_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='audios.audioproject', verbose_name='音频项目')),
            ],
            options={
                'verbose_name': '音频生成任务',
                'verbose_name_plural': '音频生成任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('script_tasks_created', models.PositiveIntegerField(default=0, verbose_name='创建的脚本任务数')),
                ('script_tasks_completed', models.PositiveIntegerField(default=0, verbose_name='完成的脚本任务数')),
                ('script_tasks_failed', models.PositiveIntegerField(default=0, verbose_name='失败的脚本任务数')),
                ('total_script_processing_time', models.FloatField(default=0, verbose_name='脚本处理总时间(秒)')),
                ('audio_tasks_created', models.PositiveIntegerField(default=0, verbose_name='创建的音频任务数')),
                ('audio_tasks_completed', models.PositiveIntegerField(default=0, verbose_name='完成的音频任务数')),
                ('audio_tasks_failed', models.PositiveIntegerField(default=0, verbose_name='失败的音频任务数')),
                ('total_audio_processing_time', models.FloatField(default=0, verbose_name='音频处理总时间(秒)')),
                ('total_audio_duration', models.FloatField(default=0, verbose_name='生成音频总时长(秒)')),
                ('llm_requests_count', models.PositiveIntegerField(default=0, verbose_name='LLM请求次数')),
                ('llm_total_tokens', models.PositiveIntegerField(default=0, verbose_name='LLM总令牌数')),
                ('llm_total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='LLM总成本')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '生成统计',
                'verbose_name_plural': '生成统计',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='ScriptGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('generation_params', models.JSONField(default=dict, verbose_name='生成参数')),
                ('emotion_analysis_enabled', models.BooleanField(default=True, verbose_name='启用情绪分析')),
                ('segment_length', models.PositiveIntegerField(default=200, verbose_name='分段长度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('analyzing', '分析中'), ('generating', '生成中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('generated_script', models.TextField(blank=True, verbose_name='生成的脚本')),
                ('emotion_analysis_result', models.JSONField(blank=True, default=dict, verbose_name='情绪分析结果')),
                ('processing_log', models.TextField(blank=True, verbose_name='处理日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_tasks', to='novels.chapter', verbose_name='源章节')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_tasks', to='novels.character', verbose_name='主要角色')),
                ('llm_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_tasks', to='llms.llmmodel', verbose_name='使用模型')),
            ],
            options={
                'verbose_name': '脚本生成任务',
                'verbose_name_plural': '脚本生成任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='工作流名称')),
                ('description', models.TextField(blank=True, verbose_name='工作流描述')),
                ('workflow_config', models.JSONField(default=dict, verbose_name='工作流配置')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否为模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('running', '运行中'), ('paused', '暂停'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('current_step', models.CharField(blank=True, max_length=100, verbose_name='当前步骤')),
                ('execution_log', models.TextField(blank=True, verbose_name='执行日志')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('audio_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='generators.audiogenerationtask', verbose_name='音频任务')),
                ('script_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='generators.scriptgenerationtask', verbose_name='脚本任务')),
            ],
            options={
                'verbose_name': '生成工作流',
                'verbose_name_plural': '生成工作流',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='audiogenerationtask',
            name='script_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tasks', to='generators.scriptgenerationtask', verbose_name='脚本任务'),
        ),
        migrations.CreateModel(
            name='ScriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='序列号')),
                ('original_text', models.TextField(verbose_name='原始文本')),
                ('processed_text', models.TextField(verbose_name='处理后文本')),
                ('emotion_confidence', models.FloatField(blank=True, null=True, verbose_name='情绪置信度')),
                ('speaker', models.CharField(blank=True, max_length=100, verbose_name='说话人')),
                ('duration_estimate', models.FloatField(blank=True, null=True, verbose_name='预估时长(秒)')),
                ('processing_notes', models.TextField(blank=True, verbose_name='处理备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('emotion_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audios.emotiontype', verbose_name='情绪类型')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='generators.scriptgenerationtask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '脚本片段',
                'verbose_name_plural': '脚本片段',
                'ordering': ['task', 'sequence_number'],
                'unique_together': {('task', 'sequence_number')},
            },
        ),
    ]
