# Generated by Django 5.2.5 on 2025-08-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0001_initial'),
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiogenerationtask',
            name='generation_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='生成参数'),
        ),
        migrations.AddField(
            model_name='audiogenerationtask',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='进度百分比'),
        ),
        migrations.AddField(
            model_name='scriptgenerationtask',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='进度百分比'),
        ),
        migrations.AddField(
            model_name='scriptgenerationtask',
            name='result',
            field=models.JSONField(blank=True, default=dict, verbose_name='结果数据'),
        ),
        migrations.AddField(
            model_name='scriptsegment',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novels.character', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='scriptsegment',
            name='content',
            field=models.TextField(default='', verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scriptsegment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
    ]
