# Generated by Django 5.2.5 on 2025-08-22 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='情绪名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='情绪代码')),
                ('description', models.TextField(blank=True, verbose_name='情绪描述')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='显示颜色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '情绪类型',
                'verbose_name_plural': '情绪类型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AudioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_projects', to='novels.chapter', verbose_name='关联章节')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_projects', to='novels.character', verbose_name='主要角色')),
            ],
            options={
                'verbose_name': '音频项目',
                'verbose_name_plural': '音频项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100, verbose_name='处理步骤')),
                ('status', models.CharField(choices=[('started', '开始'), ('processing', '处理中'), ('completed', '完成'), ('failed', '失败')], max_length=20, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='消息')),
                ('error_details', models.TextField(blank=True, verbose_name='错误详情')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='audios.audioproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '音频处理日志',
                'verbose_name_plural': '音频处理日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('voice_settings', models.JSONField(default=dict, verbose_name='语音设置')),
                ('emotion_mapping', models.JSONField(default=dict, verbose_name='情绪映射')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认模板')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_templates', to='novels.character', verbose_name='适用角色')),
            ],
            options={
                'verbose_name': '音频模板',
                'verbose_name_plural': '音频模板',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmotionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='emotion_audios/', verbose_name='音频文件')),
                ('file_type', models.CharField(choices=[('main', '主要音频'), ('short', '短音频'), ('long', '长音频'), ('alt1', '备选音频1'), ('alt2', '备选音频2')], default='main', max_length=20, verbose_name='文件类型')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('sample_rate', models.IntegerField(blank=True, null=True, verbose_name='采样率')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_audios', to='novels.character', verbose_name='角色')),
                ('emotion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='audios.emotiontype', verbose_name='情绪类型')),
            ],
            options={
                'verbose_name': '情绪音频',
                'verbose_name_plural': '情绪音频',
                'ordering': ['emotion_type', 'character', 'file_type'],
                'unique_together': {('emotion_type', 'character', 'file_type')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='文本内容')),
                ('audio_file', models.FileField(upload_to='generated_audios/', verbose_name='生成的音频文件')),
                ('sequence_number', models.PositiveIntegerField(verbose_name='序列号')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='时长(秒)')),
                ('generation_params', models.JSONField(blank=True, default=dict, verbose_name='生成参数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('emotion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.emotiontype', verbose_name='情绪类型')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_audios', to='audios.audioproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '生成音频',
                'verbose_name_plural': '生成音频',
                'ordering': ['project', 'sequence_number'],
                'unique_together': {('project', 'sequence_number')},
            },
        ),
    ]
