# Generated by Django 5.2.5 on 2025-08-22 05:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_id', models.CharField(max_length=100, verbose_name='模型ID')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('max_tokens', models.PositiveIntegerField(default=4096, verbose_name='最大令牌数')),
                ('supports_functions', models.BooleanField(default=False, verbose_name='支持函数调用')),
                ('supports_vision', models.BooleanField(default=False, verbose_name='支持视觉')),
                ('cost_per_1k_input', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='每1K输入令牌成本')),
                ('cost_per_1k_output', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='每1K输出令牌成本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'LLM模型',
                'verbose_name_plural': 'LLM模型',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='提供商名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='提供商代码')),
                ('base_url', models.URLField(verbose_name='API基础URL')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM提供商',
                'verbose_name_plural': 'LLM提供商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('category', models.CharField(choices=[('emotion_analysis', '情绪分析'), ('text_generation', '文本生成'), ('script_generation', '脚本生成'), ('content_optimization', '内容优化')], max_length=50, verbose_name='模板类别')),
                ('template_content', models.TextField(verbose_name='模板内容')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='变量列表')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('default_temperature', models.FloatField(default=0.7, verbose_name='默认温度')),
                ('default_max_tokens', models.PositiveIntegerField(default=1000, verbose_name='默认最大令牌数')),
                ('default_top_p', models.FloatField(default=1.0, verbose_name='默认Top-P')),
                ('retry_count', models.PositiveIntegerField(default=3, verbose_name='重试次数')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='超时时间(秒)')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, verbose_name='每分钟请求限制')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认配置')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='llms.llmmodel', verbose_name='默认模型')),
            ],
            options={
                'verbose_name': 'LLM配置',
                'verbose_name_plural': 'LLM配置',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='llms.llmprovider', verbose_name='提供商'),
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='密钥名称')),
                ('key_value', models.TextField(verbose_name='密钥值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='使用限制')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='llms.llmprovider', verbose_name='提供商')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['-is_active', 'provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LLMRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('emotion_analysis', '情绪分析'), ('text_generation', '文本生成'), ('script_generation', '脚本生成'), ('content_optimization', '内容优化'), ('other', '其他')], max_length=50, verbose_name='请求类型')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('response', models.TextField(blank=True, verbose_name='响应内容')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='输入令牌数')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='输出令牌数')),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='总令牌数')),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='成本')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='响应时间(秒)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('request_params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='llms.apikey', verbose_name='使用密钥')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='llms.llmmodel', verbose_name='使用模型')),
            ],
            options={
                'verbose_name': 'LLM请求记录',
                'verbose_name_plural': 'LLM请求记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='llmmodel',
            unique_together={('provider', 'model_id')},
        ),
    ]
