# Generated by Django 5.2.5 on 2025-08-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llmrequest',
            old_name='request_params',
            new_name='parameters',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='key_value',
        ),
        migrations.RemoveField(
            model_name='llmrequest',
            name='response_time',
        ),
        migrations.AddField(
            model_name='apikey',
            name='api_key',
            field=models.TextField(default='', verbose_name='API密钥'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='context_length',
            field=models.PositiveIntegerField(default=4096, verbose_name='上下文长度'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='input_price_per_token',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='输入价格/令牌'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='model_type',
            field=models.CharField(choices=[('text', '文本生成'), ('chat', '对话模型'), ('embedding', '嵌入模型'), ('image', '图像模型')], default='text', max_length=50, verbose_name='模型类型'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='output_price_per_token',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='输出价格/令牌'),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)'),
        ),
        migrations.AddField(
            model_name='llmrequest',
            name='request_id',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='请求ID'),
            preserve_default=False,
        ),
    ]
