# Generated by Django 5.2.5 on 2025-08-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0002_rename_request_params_llmrequest_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='is_default_assistant',
            field=models.BooleanField(default=False, verbose_name='是否为默认管家'),
        ),
    ]
